name: CI

on:
  push:
    branches: "master"
    tags: ["*"]
  pull_request:
  release:

env:
  PYTHON: Conda 
  LD_LIBRARY_PATH: /home/runner/.julia/conda/3/x86_64/lib
  
jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - "1.6"
          - "1"
          - "nightly"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        julia-arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v1 # https://github.com/julia-actions/cache
      - uses: julia-actions/julia-buildpkg@latest
      - name: "Install Conda"
        if: $${{runner.os == 'Linux' && matrix.version == '1.6'}}
        run: |
              julia -e 'using Pkg; Pkg.add("Conda");'
              cd $LD_LIBRARY_PATH
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@v0.1
        continue-on-error: true
      - uses: julia-actions/julia-uploadcoveralls@v0.1
        continue-on-error: true

  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6
          arch: x64
      - uses: julia-actions/cache@v1 # https://github.com/julia-actions/cache
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
